services:
  db:
    image: postgres:15-alpine
    container_name: openedulog-postgres
    restart: always
    environment:
      POSTGRES_USER: openeduuser
      POSTGRES_PASSWORD: openedupassword
      POSTGRES_DB: open_edu_log
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
